---
title: "intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("readr")
library(readr)
library(ggplot2)
```

```{r}
getwd()

```

```{r eval= TRUE}
trees <- read_tsv(file ="../data-raw/TREE_SURVEYS.txt",
               col_types = list(HEIGHT = col_double(),
                                AXIS_2 = col_double()))
```

```{r}
head(trees)
str(trees)
```

```{r}
canopy_area <- trees$AXIS_1 * trees$AXIS_2
canopy_area
trees$canopy_area <- canopy_area
head(trees)
```

```{r}
subset(trees, select = c(SURVEY, YEAR,SITE, canopy_area))
```

```{r}
library(ggplot2)
ggplot(data = trees, mapping = aes(x = canopy_area, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 2) +
  facet_wrap(~SPECIES)
```

```{r}
3 > 4
numbers <- 1:10
numbers > 4
canopy_area > 2000
which(canopy_area > 2000)
canopy_area[3839]
canopy_area[-3839]
numbers[-4]
```

```{r}
trees2 <- trees[-3839,]
```

```{r}
ggplot(data = trees2, mapping = aes(x = canopy_area, y = HEIGHT,  color = TREATMENT)) +
geom_point(size = 2) +
  facet_wrap(~TREATMENT)
```
names(trees)
?read.csv
?geom_smooth
mode(trees$CIRC)
mode(trees$HEIGHT)
mode(aca$CIRC)
mode(aca$HEIGHT)
```{r}
library(ggplot2)
aca <- read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t", na.strings = "dead")
ggplot() +
  geom_point(data = trees, mapping = aes(x = CIRC, y = HEIGHT), size = 3, alpha = 0.5, color = "gray") +
  labs(x = "Circumference", y = "Height") +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm") +
  geom_line() +
  geom_point(data = aca, mapping = aes(x = CIRC, y = HEIGHT, color = "red")) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm") +
  geom_line()
```

```{r}
ac <- read.csv(file = "../data-raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t", na.strings = "dead")
trees <- read_tsv(file ="../data-raw/TREE_SURVEYS.txt",
               col_types = list(HEIGHT = col_double(),
                                AXIS_2 = col_double()))
```


```{r}
ggplot() +
  geom_point(data = trees, mapping = aes(x = CIRC, y = HEIGHT), color = "gray", alpha = 0.5) +
  geom_point(color = "gray") +
  geom_point(data = ac, mapping = aes(x = CIRC, y = HEIGHT), color = "red", alpha = 0.6) +
  scale_x_log10() +
  scale_y_log10() +
  geom_smooth(method = "lm") +
  geom_smooth(data = ac, mapping = aes(x = CIRC, y = HEIGHT), method = "lm") +
  geom_smooth(data = trees, mapping = aes(x = CIRC, y = HEIGHT), method = "lm")
```
